#!/bin/bash
# ///
# ///
# /// @file	vdemo
# /// @author	Marc Hanheide (mhanheid@TechFak.Uni-Bielefeld.de)
# /// @date	started at 2005/03/04
# /// @version	$Id: vdemo2,v 1.3 2007/08/17 15:28:46 mhanheid Exp $
# ///
# /// @brief       vdemo not documented yet (read source yourself ;-) )
# /// 
# /// 
# /// $Log: vdemo2,v $
# /// Revision 1.3  2007/08/17 15:28:46  mhanheid
# /// some forgotten changes and xterm with better colors
# ///
# /// Revision 1.2  2006/11/07 16:39:22  mhanheid
# /// *** empty log message ***
# ///
# /// Revision 1.1  2006/11/07 06:35:09  mhanheid
# /// version 2 added
# ///
# /// Revision 1.2  2005/12/01 15:16:41  mhanheid
# /// corrected shell setting
# ///
# /// Revision 1.1  2005/11/24 15:59:04  mhanheid
# /// initial
# ///
# /// Revision 1.3  2005/05/03 12:19:57  mhanheid
# /// *** empty log message ***
# ///
# /// Revision 1.2  2005/05/03 11:56:49  mhanheid
# /// *** empty log message ***
# ///
# /// Revision 1.2  2005/04/08 15:00:18  mhanheid
# /// *** empty log message ***
# ///
# /// Revision 1.1  2005/04/06 11:08:23  mhanheid
# /// Initial revision
# ///
# /// Revision 1.1  2005/03/04 10:43:42  mhanheid
# /// *** empty log message ***
# ///
# /// Revision 1.1  2005/01/05 10:47:16  mhanheid
# /// Initial revision
# ///
# ///

# ************************************* START *********************************
#!/bin/bash

# defaults:
RCS_ID='$Id: vdemo2,v 1.3 2007/08/17 15:28:46 mhanheid Exp $'
SCRIPTNAME=`basename $0`

USAGE="\
usage: $SCRIPTNAME [options] <Config file>
  for further help invoke '$SCRIPTNAME -h'
"

HELP="\
usage: $SCRIPTNAME [options] <Config file>

vdemo starter

 options:
  -v  --var          set some variables (like: \"laptop='dyn-laptop-33' host1='mondrian' host2='kandinsky'\")
  -h  --help         this help text

 author: Marc Hanheide ($RCS_ID)
"
VARS=""
# option checks
while [ $# -gt 0 ]; do
    case $1 in
	"-h"|"--help")
	    echo "$HELP" >& 2
	    exit 0
	    ;;
	"-v"|"--var")
	    shift
	    echo "otion -v is no longer supported!" >&2
	    VARS="$1"
	    ;;
	-*)
	    echo "illegal option $1" >& 2
	    echo "$USAGE" >& 2
	    exit 1
	    ;;
	*)	    
	    break
	    ;;
    esac
    shift
done

# obligatory arguments check
if [ $# -lt 1 ]; then
    echo "obligatory argument(s) missing. $USAGE" >&2 
    exit 1
fi

eval $VARS

if [ -z "/tmp/hurga/lib/vdemo" ]; then
    VDEMO_root="/tmp/hurga/lib/vdemo"
    echo 'VDEMO_root=/tmp/hurga/lib/vdemo (per default)' >&2
fi


VDEMO_demoConfig="$1"
source "$VDEMO_demoConfig"

export VDEMO_demoConfig VDEMO_root


$VDEMO_root/vdemo2_controller.tcl



# ******************************** EOF vdemo *********************************

